name: Neuro-Divergent CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'neuro-divergent/**'
      - '.github/workflows/neuro-divergent-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'neuro-divergent/**'
  schedule:
    # Weekly comprehensive test on Sundays
    - cron: '0 3 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        python: [3.8, 3.9, '3.10', '3.11']
        include:
          - os: ubuntu-latest
            rust: 1.81.0  # MSRV
          - os: ubuntu-latest
            rust: stable
            gpu: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          neuro-divergent/target
          neuro-divergent/**/target
        key: ${{ runner.os }}-neuro-divergent-${{ matrix.rust }}-py${{ matrix.python }}-${{ hashFiles('neuro-divergent/Cargo.lock', 'neuro-divergent/**/Cargo.lock') }}

    - name: Check formatting
      if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
      working-directory: neuro-divergent
      run: cargo fmt --all -- --check

    - name: Run clippy
      if: matrix.rust == 'stable'
      working-directory: neuro-divergent
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build workspace
      working-directory: neuro-divergent
      run: cargo build --verbose --all-features

    - name: Run tests
      working-directory: neuro-divergent
      run: cargo test --all-features --verbose

    - name: Run doctests
      working-directory: neuro-divergent
      run: cargo test --doc --all-features

    - name: Test Python compatibility
      if: matrix.os == 'ubuntu-latest' && matrix.python == '3.11'
      working-directory: neuro-divergent
      run: |
        pip install numpy pandas polars
        python -c "import sys; print(f'Python {sys.version}'); import numpy as np; print(f'NumPy {np.__version__}')"

    - name: Test GPU features (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.gpu == true
      working-directory: neuro-divergent
      run: cargo test --features gpu -- --test-threads=1

  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          neuro-divergent/target
        key: ${{ runner.os }}-neuro-divergent-bench-${{ hashFiles('neuro-divergent/Cargo.lock') }}

    - name: Run benchmarks
      working-directory: neuro-divergent
      run: cargo bench --all-features

    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      if: github.ref == 'refs/heads/main'
      with:
        tool: 'cargo'
        output-file-path: neuro-divergent/target/criterion/report/index.html
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        alert-threshold: '150%'
        fail-on-alert: true

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'main'

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          neuro-divergent/target
        key: ${{ runner.os }}-neuro-divergent-coverage-${{ hashFiles('neuro-divergent/Cargo.lock') }}

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage
      working-directory: neuro-divergent
      run: cargo tarpaulin --verbose --all-features --workspace --timeout 300 --out xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./neuro-divergent/cobertura.xml
        flags: neuro-divergent
        fail_ci_if_error: false

  cross-compile:
    name: Cross Compilation
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-musl
          - wasm32-unknown-unknown

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Cross-compile
      working-directory: neuro-divergent
      run: |
        if [ "${{ matrix.target }}" = "wasm32-unknown-unknown" ]; then
          cargo build --target ${{ matrix.target }} --all-features
        else
          cross build --target ${{ matrix.target }} --all-features --release
        fi

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      working-directory: neuro-divergent
      run: cargo audit

    - name: Install cargo-deny
      run: cargo install cargo-deny

    - name: Check licenses and advisories
      working-directory: neuro-divergent
      run: cargo deny check

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          neuro-divergent/target
        key: ${{ runner.os }}-neuro-divergent-docs-${{ hashFiles('neuro-divergent/Cargo.lock') }}

    - name: Build documentation
      working-directory: neuro-divergent
      run: cargo doc --all-features --no-deps --document-private-items

    - name: Deploy documentation
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./neuro-divergent/target/doc
        destination_dir: neuro-divergent
        force_orphan: true

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install numpy pandas polars scikit-learn
        sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          neuro-divergent/target
        key: ${{ runner.os }}-neuro-divergent-integration-${{ hashFiles('neuro-divergent/Cargo.lock') }}

    - name: Build integration test binary
      working-directory: neuro-divergent
      run: cargo build --example complete_workflow --release

    - name: Run integration tests
      working-directory: neuro-divergent
      run: |
        timeout 300s cargo run --example complete_workflow || [ $? -eq 124 ]
        timeout 300s cargo run --example ensemble_forecasting || [ $? -eq 124 ]

  release-check:
    name: Release Readiness
    runs-on: ubuntu-latest
    needs: [test, benchmark, coverage, cross-compile, security-audit, integration-test]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check if version bumped
      id: version-check
      working-directory: neuro-divergent
      run: |
        if git diff HEAD~1 Cargo.toml | grep -q "^+version"; then
          echo "version_bumped=true" >> $GITHUB_OUTPUT
        else
          echo "version_bumped=false" >> $GITHUB_OUTPUT
        fi

    - name: Validate changelog
      if: steps.version-check.outputs.version_bumped == 'true'
      working-directory: neuro-divergent
      run: |
        if ! grep -q "## \[$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')\]" CHANGELOG.md; then
          echo "Version bump detected but CHANGELOG.md not updated"
          exit 1
        fi

    - name: Check workspace packages
      working-directory: neuro-divergent
      run: cargo package --all-features

    - name: Check publish readiness
      working-directory: neuro-divergent
      run: cargo publish --dry-run --all-features